### ISSUE TITLE
Static content does not deploy correctly on Windows 10 host

### ISSUE THREAD

**Issue by joshuaswarren** [joshuaswarren/magescotch#19]
Possibly related to #17 - the demo content in M2 installs fine to http://192.168.33.10/magento2/ but the pages have no graphics due to errors such as this:

`Cannot create a symlink for "/var/www/public/magento2/app/design/frontend/Magento/luma/web/images/logo.svg" and place it to "/var/www/public/magento2/pub/static/frontend/Magento/luma/en_US/images/logo.svg" Warning!symlink(): Protocol error
#0 /var/www/public/magento2/lib/internal/Magento/Framework/Filesystem/Directory/Write.php(155): Magento\Framework\Filesystem\Driver\File->symlink('/var/www/public...', '/var/www/public...', Object(Magento\Framework\Filesystem\Driver\File))
#1 /var/www/public/magento2/lib/internal/Magento/Framework/App/View/Asset/MaterializationStrategy/Symlink.php(30): Magento\Framework\Filesystem\Directory\Write->createSymlink('logo.svg', 'frontend/Magent...', Object(Magento\Framework\Filesystem\Directory\Write))
#2 /var/www/public/magento2/lib/internal/Magento/Framework/App/View/Asset/Publisher.php(78): Magento\Framework\App\View\Asset\MaterializationStrategy\Symlink->publishFile(Object(Magento\Framework\Filesystem\Directory\Write), Object(Magento\Framework\Filesystem\Directory\Write), 'logo.svg', 'frontend/Magent...')
#3 /var/www/public/magento2/lib/internal/Magento/Framework/App/View/Asset/Publisher.php(61): Magento\Framework\App\View\Asset\Publisher->publishAsset(Object(Magento\Framework\View\Asset\File))
#4 /var/www/public/magento2/lib/internal/Magento/Framework/App/StaticResource.php(102): Magento\Framework\App\View\Asset\Publisher->publish(Object(Magento\Framework\View\Asset\File))
#5 /var/www/public/magento2/lib/internal/Magento/Framework/App/Bootstrap.php(258): Magento\Framework\App\StaticResource->launch()
#6 /var/www/public/magento2/pub/static.php(13): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\StaticResource))
#7 {main}`

**Comment by joshuaswarren** [comment]
This will most likely be resolved by #21 according to https://github.com/mitchellh/vagrant/issues/6024
