### ISSUE TITLE
File permission issues block setup:di:compile

### ISSUE THREAD

**Issue by joshuaswarren** [joshuaswarren/magescotch#22]
Even running as root within the VM:

bin/magento setup:di:compile
The file "/var/www/public/magento2/var/generation/Magento/CatalogSearch/Model/Adapter/Mysql/Aggregation/DataProvider/Interceptor.php" cannot be deleted Warning!unlink(/var/www/public/magento2/var/generation/Magento/CatalogSearch/Model/Adapter/Mysql/Aggregation/DataProvider/Interceptor.php): Permission denied#0 /var/www/public/magento2/lib/internal/Magento/Framework/Filesystem/Driver/File.php(405): Magento\Framework\Filesystem\Driver\File->deleteFile('/var/www/public...')
#1 /var/www/public/magento2/lib/internal/Magento/Framework/Filesystem/Driver/File.php(403): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/var/www/public...')
#2 /var/www/public/magento2/lib/internal/Magento/Framework/Filesystem/Driver/File.php(403): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/var/www/public...')
#3 /var/www/public/magento2/lib/internal/Magento/Framework/Filesystem/Driver/File.php(403): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/var/www/public...')
#4 /var/www/public/magento2/lib/internal/Magento/Framework/Filesystem/Driver/File.php(403): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/var/www/public...')
#5 /var/www/public/magento2/lib/internal/Magento/Framework/Filesystem/Driver/File.php(403): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/var/www/public...')
#6 /var/www/public/magento2/lib/internal/Magento/Framework/Filesystem/Driver/File.php(403): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/var/www/public...')
#7 /var/www/public/magento2/lib/internal/Magento/Framework/Filesystem/Driver/File.php(403): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/var/www/public...')
#8 /var/www/public/magento2/setup/src/Magento/Setup/Console/CompilerPreparation.php(68): Magento\Framework\Filesystem\Driver\File->deleteDirectory('/var/www/public...')
#9 /var/www/public/magento2/lib/internal/Magento/Framework/Console/Cli.php(74): Magento\Setup\Console\CompilerPreparation->handleCompilerEnvironment()
#10 /var/www/public/magento2/bin/magento(22): Magento\Framework\Console\Cli->__construct('Magento CLI')
#11 {main}

PHP Fatal error:  Uncaught Error: Class 'Cli' not found in /var/www/public/magento2/bin/magento:31
Stack trace:
#0 {main}
  thrown in /var/www/public/magento2/bin/magento on line 31

**Comment by joshuaswarren** [comment]
This appears to be resolved in MageMalt 2.0.14.
